apiVersion: v1
kind: PersistentVolumeClaim
metadata:
#######################################################################################
## Specify the name to use for the volume claim.  If using a NFS volume, this MUST match
## the claim name designation in the persistent volume yaml file.
#######################################################################################
  name: <Volume Claim Name>
spec:
#######################################################################################
## Specify the access mode. Choices are "ReadWriteMany" for volumes to be shared across microservices,
## "ReadWriteOnce" for volumes accessed by a single microservice, or "ReadOnly", which as implies,
## does not allow writes.
#######################################################################################
  accessModes:
    - <ReadWriteMany|ReadWriteOnce|ReadOnly>
  resources:
    requests:
#######################################################################################
## Specify the size of the requested volume using Mi for megabytes, or Gi for gigabytes
#######################################################################################
      storage: <10Gi>
########################################################################
## For Dynamically generated volumes set storageClassName to
##  "glusterfs-storage" and remove the volumeName line.
## For NFS volumes, leave storageClassName empty set  "", and set volumeName
## to the NFS volume name defined in your persistent-volume.yaml
########################################################################
  storageClassName: ""
  volumeName: <persistent-volume-name>
