######################################################################
##
## The following template can be used as is for defining most CronJobs.
## The parameters defined within should allow you to configure a CronJob
## to any degree you need.  With minor exceptions documented below, DO NOT
## edit the template; e.g. you need sidecar container. If you need additional
## parameters, use kustomize and template-defs.json per the el-CICD documention
## to add them.
##
######################################################################
apiVersion: v1
kind: Template
labels:
  template: cronjob-template
message: Deploying using templated resources
metadata:
  name: cronjob-template
objects:
- apiVersion: batch/v1beta1
  kind: CronJob
  metadata:
    name: ${APP_NAME}
  spec:
    concurrencyPolicy: Allow
    failedJobsHistoryLimit: 3
    jobTemplate:
      metadata:
      spec:
        template:
          metadata:
          spec:
            containers:
            - command:
############################################################################
##
## The interpreter and or executable parameters mey need to be a quoted string
## if the executable requires a additional arguments, such as:
##
## '/opt/app-root/src/app.py arg1'
##
############################################################################
              - ${INTERPRETER}
              - ${EXECUTABLE}
              image: ${IMAGE_REPOSITORY}/${PROJECT_ID}-${MICROSERVICE_NAME}:${IMAGE_TAG}
              name: ${APP_NAME}
              imagePullPolicy: Always
            imagePullSecrets:
            - name: ${PULL_SECRET}
              resources:
                limits:
                  cpu: ${CPU_LIMIT}
                  memory: ${MEM_LIMIT}
                requests:
                  cpu: ${CPU_REQ}
                  memory: ${MEM_REQ}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
            dnsPolicy: ClusterFirst
            restartPolicy: OnFailure
            schedulerName: default-scheduler
            securityContext: {}
            terminationGracePeriodSeconds: 30
    schedule: ${SCHEDULE}
############################################################################
##
## The schedule is defined as a parameter, and as such will need to be a quoted string; e.g:
##
## '*/10 * * * *'
##
## CronJobs use standard cron notation for scheduling.
##
############################################################################
    successfulJobsHistoryLimit: 3
    suspend: false

parameters:
- description: The image repository from where to fetch the image
  displayName: Image Repository
  name: IMAGE_REPOSITORY
  required: true

- description: The name for the microservice, derived by el-CICD from the name of the Git repository
  displayName: Microservice Name
  name: MICROSERVICE_NAME
  required: true

- description: The name for the app.  Set this value manually through the template-defs.json file for multiple deployments of the same image.
  displayName: Application Name
  name: APP_NAME
  required: true

- description: The Project ID
  displayName: Project ID
  name: PROJECT_ID
  required: true

- description: The name of the environment the image is being deployed to.  Used to help define unique routes.
  displayName: Environment Name
  name: ENV
  required: true

- description: Image Tag used to pull image from image repository
  displayName:  Image Tag
  name: IMAGE_TAG
  required: true

- description: CPU Resource Request; see OKD docs for more info
  displayName: CPU Resource Request
  name: CPU_REQ
  required: true
  value: 100m

- description: Maximum CPU Resource Limit allowed; see OKD docs for more info
  displayName: CPU Resource Limit
  name: CPU_LIMIT
  required: true
  value: 200m

- description: Memory Resource Request; see OKD docs for more info
  displayName: Memory Resource Request
  name: MEM_REQ
  required: true
  value: 50Mi

- description: Memory Resource Limit (Ceiling) in Mi or Gi; see OKD docs for more info
  displayName: Memory Resource Limit in Mi or Gi
  name: MEM_LIMIT
  required: true
  value: 500Mi

- description: Interpreter program to run 
  displayName: Interpreter program
  name: INTERPRETER
  required: true

- description: Full path to executable program
  displayName: executable program
  name: EXECUTABLE
  required: true

- description: cronjob schedule
  displayName: cronjob schedule, using standard cron notation
  name: SCHEDULE
  required: true
